# Q1. 
What are the benefits of the built-in array package, if any?

<b>Answer:</b><br>
The built-in array package in Python has several benefits, including:<br>

1.`Efficient memory management`: Python's array module manages memory efficiently, allowing you to work with large arrays without worrying about memory allocation issues.<br>
2.`Vectorized operations`: Many mathematical operations in NumPy are vectorized, meaning they can operate on entire arrays at once, rather than having to iterate over each element individually. This leads to significant performance improvements for many tasks.<br>
3.`High-performance computing`: NumPy arrays are optimized for high-performance computing and are often faster than lists or other data structures for certain tasks.<br>
4.`Integration with other libraries`: NumPy arrays can be easily integrated with other popular scientific computing libraries, such as Pandas, Scipy, and Matplotlib, making it easy to perform advanced data analysis and visualization tasks.<br>
5.`Homogeneous data structure`: All elements in an NumPy array must be of the same data type, which makes it easier to perform operations on the data since you don't have to worry about handling different data types.<br>
6.`Support for multi-dimensional arrays`: NumPy supports multi-dimensional arrays, which can be useful for representing data with multiple variables or dimensions.<br>
7.`Broadcasting`: NumPy arrays support broadcasting, which allows you to perform operations on arrays with different shapes and sizes.<br>
8.`Random number generation`: NumPy provides functions for generating random numbers, which can be useful for simulations, modeling, and statistical analysis.<br>
9.`Sorting and indexing`: NumPy arrays can be sorted and indexed quickly and efficiently, making it easy to find specific values or reorder the data.<br>
10.`Data manipulation`: NumPy provides a range of functions for manipulating data, such as reshaping, transposing, flattening, and more.<br>

# Q2.
What are some of the array package&#39;s limitations?

<b>Answer:</b><br>
1.The number of elements to be stored in an array should be known in advance. An array is a static structure (which means the array is of fixed size). Once declared the size of the array cannot be modified. The memory which is allocated to it cannot be increased or decreased.<br>
2.Insertion and deletion are quite difficult in an array as the elements are stored in consecutive memory locations and the shifting operation is costly.<br>
3.Allocating more memory than the requirement leads to wastage of memory space and less allocation of memory also leads to a problem<br>

# Q3.
Describe the main differences between the array and numpy packages.

<b>Answer:</b><br>
1.The array package doesn't provide any help with numerical calculation with the items insdie it in number form while NumPy give you a wide variety of numerical operations.<br>
2.An array is a single dimensional entity which hold the numerical data, while numpy can have more than 1 dimension.<br>
3.In case of array, item can be accessed by its index position and it is easy task while in numpy item is accessed by its column and row index, which makes it slightly time taking. Same goes with appending operation.<br>
4.In case of array we do not form a tabular structure, while in numpy it forms a tabular structure<br>

# Q4.
Explain the distinctions between the empty, ones, and zeros functions.

<b>Answer:</b><br>
The distinctions between the empty, ones, and zero functions are as follows :<br>

1.Empty function: An empty function is a function that does not contain any statement within its body. If you try to write a function definition without any statement in python ,it will return an error. To avoid this, we use pass statement. pass is a special statement in Python that does nothing. It only works as a dummy statement.<br>
2.Ones: This function returns a new array of given shape and data type, where the element’s value is 1.<br>
3.Zeros: This function returns a new array of given shape and data type, where the element’s value is 0.<br>

# Q5. 
In the fromfunction function, which is used to construct new arrays, what is the role of the callable
argument?

<b>Answer:</b><br>In the `fromfunction function`, the `callable argument` is used to generate the values for the new array. The callable is a function that takes in a single argument, which is the index of the element in the new array, and returns the value that should be assigned to that element.

# Q6.
What happens when a numpy array is combined with a single-value operand (a scalar, such as
an int or a floating-point value) through addition, as in the expression A + n?

<b>Answer:</b><br>When a NumPy array is combined with a single-value operand (a scalar, such as an integer or a floating-point value) through addition, the result is a new NumPy array with the same shape as the original array, but with its elements updated by adding the scalar value to each element of the original array.

In [6]:
import numpy as np

A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = A + 3
B

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# Q7.
Can array-to-scalar operations use combined operation-assign operators (such as += or *=)?
What is the outcome?

<b>Answer:</b><br>Yes, array-to-scalar operations can use combined operation-assign operators  `(such as += or *=)` in NumPy. These operators perform the desired operation and assign the result to the original array.

In [7]:
import numpy as np

# Create an example array
arr = np.array([1, 2, 3, 4, 5])

# Use combined operation-assign operators
arr += 2
print(arr)  # Output: [3, 4, 5, 6, 7]

arr *= 3
print(arr)  # Output: [9, 12, 15, 18, 21]



[3 4 5 6 7]
[ 9 12 15 18 21]


# Q8.
Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to
one of these arrays?

<b>Answer:</b><br>Yes, it is possible that we can include a string of fixed length in numpy array. The dtype of any numpy array containing string values is the maximum length of any string present in the array.Once set, it will only be able to store new string having length not more than the maximum length at the time of the creation. If we try to reassign some another string value having length greater than the maximum length of the existing elements, it simply discards all the values beyond the maximum length accept upto those values which are under the limit.

# Q9.
What happens when you combine two numpy arrays using an operation like addition (+) or
multiplication (*)? What are the conditions for combining two numpy arrays?

<b>Answer:</b><br>
It will simply add or multiply element to element at same position.<br>
The conditions for combining two NumPy arrays using + or * are:<br>
1.The arrays must have compatible shapes for element-wise operations.<br>
2.If the shapes are not compatible, a ValueError will be raised.<br>

# Q10.
What is the best way to use a Boolean array to mask another array?

<b>Answer:</b><br>
The best way to use a Boolean array to mask another array in NumPy is by using Boolean indexing. Boolean indexing allows you to select elements from one array based on the corresponding Boolean values in another array. 

In [8]:
import numpy as np

# Create a NumPy array
data = np.array([1, 2, 3, 4, 5])

# Create a Boolean mask based on a condition
mask = (data > 2)  # This creates a Boolean array where each element indicates whether the condition is True

# Use the Boolean mask to select elements from the original array
result = data[mask]

print(result)

[3 4 5]


# Q11.
What are three different ways to get the standard deviation of a wide collection of data using
both standard Python and its packages? Sort the three of them by how quickly they execute.

<b>Answer:</b><br>
1.NumPy's numpy.std() Function (Fastest):<br>
NumPy is optimized for numerical operations and is typically the fastest way to calculate the standard deviation of an array.<br>

In [9]:
import numpy as np

data = np.array([1, 2, 3, 4, 5])
std_dev = np.std(data)

2.Statistics Module (Standard Library):<br>

Python's standard library includes the statistics module, which provides a stdev() function for calculating the standard deviation.<br>
While not as fast as NumPy for large datasets, it's still a reliable option for standard deviation calculation.

In [10]:
import statistics

data = [1, 2, 3, 4, 5]
std_dev = statistics.stdev(data)

3.Manual Calculation (Slower):<br>
You can calculate the standard deviation manually by following the mathematical formula

In [11]:
data = [1, 2, 3, 4, 5]
mean = sum(data) / len(data)
squared_diff = [(x - mean) ** 2 for x in data]
std_dev = (sum(squared_diff) / len(data)) ** 0.5

# 12.
What is the dimensionality of a Boolean mask-generated array?

<b>Answer:</b><br>: It will have same dimensionality as input array